# Generated by Django 4.2.6 on 2023-10-21 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shogi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
    ]
