# Generated by Django 4.2.6 on 2023-10-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shogi', '0002_remove_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='encode_game',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
