# Generated by Django 4.2.6 on 2023-10-24 03:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Shogi', '0003_game_encode_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='encode_game',
        ),
        migrations.RemoveField(
            model_name='game',
            name='id',
        ),
        migrations.AddField(
            model_name='game',
            name='binary_game',
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='move_records',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_won', to='Shogi.player'),
        ),
        migrations.DeleteModel(
            name='Move',
        ),
    ]
