# Generated by Django 4.2.6 on 2023-10-24 04:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Shogi', '0004_remove_game_encode_game_remove_game_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
