# Generated by Django 4.2.6 on 2023-10-24 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shogi', '0005_alter_game_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='victories',
            new_name='losses',
        ),
        migrations.RemoveField(
            model_name='game',
            name='move_records',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='opponents',
        ),
        migrations.AddField(
            model_name='game',
            name='game_record',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='game',
            name='loser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_lost', to='Shogi.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='opponent_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_as_opponent_player', to='Shogi.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='our_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_as_our_player', to='Shogi.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Finished', 'Finished')], default='Ongoing', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='binary_game',
            field=models.BinaryField(default=b''),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_won', to='Shogi.player'),
        ),
    ]
