# Generated by Django 4.2.6 on 2023-10-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shogi', '0006_rename_victories_player_losses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='round',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
