# Generated by Django 4.2.6 on 2023-10-30 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shogi', '0007_game_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='round',
        ),
    ]
